export {default as Login} from "./login/login"
export {default as Register} from "./register/register"
export {default as Verify} from "./verify/Verify"
export {default as ForgotPassword} from "./forgotPassword/forgotPassword"
export {default as VerifyForgot} from "./verifyForgotPassword/VerifyForgotPassword"
