export {default as Login} from "./login/Login"
export {default as Register} from "./register/Register"
export {default as Verify} from "./verify/Verify"
export {default as ForgotPassword} from "./forgotPassword/ForgotPasswords"
export {default as VerifyForgot} from "./verifyForgotPassword/VerifyForgotPassword"
